import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar, Footer } from "./componen/component";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "U-nime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className='bg-slate-950 text-white'>
      <Navbar />
        {children}


      <Footer />
      
      </body>
    </html>
  );
}
